language: python

sudo: false

env:
    - TOX_ENV=py27-django19-drf3.4
    - TOX_ENV=py27-django19-drf3.6
    - TOX_ENV=py35-django19-drf3.4
    - TOX_ENV=py35-django19-drf3.6
    - TOX_ENV=py27-django110-drf3.4
    - TOX_ENV=py27-django110-drf3.6
    - TOX_ENV=py35-django110-drf3.4
    - TOX_ENV=py35-django110-drf3.6
    - TOX_ENV=lint
    - TOX_ENV=docs

matrix:
    fast_finish: true

install:
    - pip install tox-travis

script:
    - tox -e $TOX_ENV

after_success:
    - pip install codecov
    - codecov -e TOXENV
