language: python

python:
    - "2.7"
    - "3.5"

sudo: false

env:
    - TOX_ENV=django19-drf3.4
    - TOX_ENV=django19-drf3.6
    - TOX_ENV=django19-drf3.4
    - TOX_ENV=django19-drf3.6
    - TOX_ENV=django110-drf3.4
    - TOX_ENV=django110-drf3.6
    - TOX_ENV=django110-drf3.4
    - TOX_ENV=django110-drf3.6

matrix:
    fast_finish: true
    include:
        - python: "2.7"
          env: TOX_ENV="lint"
        - python: "2.7"
          env: TOX_ENV="docs"

install:
    - pip install tox-travis

script:
    - tox -e $TOX_ENV

after_success:
    - pip install codecov
    - codecov -e TOX_ENV

notifications:
    email: false
